ex1:ex1.c
	gcc -Wall -g -o ex1 ex1.c

input:input.c
	gcc -Wall -g -o input input.c

ex2_sv:ex2_sv.c
	gcc -Wall -g -o ex2_sv ex2_sv.c

ex4:ex4.c
	gcc -Wall -g -o ex4 ex4.c

ex5:ex5.c
	gcc -Wall -g -o ex5 ex5.c

ex6:ex6.c
	gcc -Wall -g -o ex6 ex6.c
