myreadlnc:myreadlncaracter.c
	gcc -Wall -g -o myreadlnc myreadlncaracter.c

myreadlnl:myreadlnlinhas.c
	gcc -Wall -g -o myreadlnl myreadlnlinhas.c

myreadlnc2:myreadlncaracter2.c
	gcc -Wall -g -D__TEST__ -o myreadlnc2 myreadlncaracter2.c

myreadlnl2:myreadlnlinhas2.c
	gcc -Wall -g -D__TEST__ -o myreadlnl2 myreadlnlinhas2.c
