ex1:ex1.c
	gcc -Wall -g -o ex1 ex1.c

ex2:ex2.c
	gcc -Wall -g -o ex2 ex2.c

ex3:ex3.c
	gcc -Wall -g -o ex3 ex3.c

ex4:ex4.c
	gcc -Wall -g -o ex4 ex4.c

ex5:ex5.c
	gcc -Wall -g -o ex5 ex5.c

ex6:ex6.c
	gcc -Wall -g -o ex6 ex6.c
