ex1:ex1.c
	gcc -Wall -g -o ex1 ex1.c

ex2_sv:ex2_sv.c
	gcc -Wall -g -o ex2_sv ex2_sv.c

ex2_sv_2.0:ex2_sv_2.0.c
	gcc -Wall -g -o ex2_sv_2.0 ex2_sv_2.0.c

ex4:ex4.c
	gcc -Wall -g -o ex4 ex4.c

ex5:ex5.c
	gcc -Wall -g -o ex5 ex5.c

input:input.c
	gcc -Wall -g -o input input.c
