echo Script running $1

make pessoas
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23
./pessoas -i "OLA" 9
./pessoas -i "aaaaa" 24
./pessoas -u "aaaaa" 23

